import type { Metadata } from "next";
import { Geist, Geist_Mono} from "next/font/google";
import { LanguageProvider } from "./components/shared/i18n";
import "../app/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "IZA POS V2",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          suppressHydrationWarning
          dangerouslySetInnerHTML={{
            __html: `
              (() => {
                const attribute = "bis_skin_checked";
                const clean = (root = document) => {
                  root.querySelectorAll?.("[" + attribute + "]").forEach((element) => {
                    element.removeAttribute(attribute);
                  });
                };

                clean();
                const observer = new MutationObserver((mutations) => {
                  for (const mutation of mutations) {
                    if (mutation.type === "attributes" && mutation.target instanceof Element) {
                      mutation.target.removeAttribute(attribute);
                    }
                  }
                });
                observer.observe(document.documentElement, {
                  attributes: true,
                  subtree: true,
                  attributeFilter: [attribute],
                });
                document.addEventListener("DOMContentLoaded", () => clean(), { once: true });
                window.addEventListener("load", () => {
                  clean();
                  window.setTimeout(() => observer.disconnect(), 1000);
                }, { once: true });
              })();
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <LanguageProvider>{children}</LanguageProvider>
      </body>
    </html>
  );
}
